# Generated by Django 5.1.2 on 2024-10-22 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publick_key",
                    models.CharField(
                        help_text="Yandex.Disk public link key",
                        max_length=255,
                        verbose_name="Public Key",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who added this link",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Link",
                "verbose_name_plural": "Public Links",
                "ordering": ["-last_accessed"],
            },
        ),
    ]
